[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
fuji = "${FUJI_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"
mainnet = "${MAINNET_RPC_URL}"
mumbai = "${MUMBAI_RPC_URL}"
polygon = "${POLYGON_RPC_URL}"
sepolia = "${SEPOLIA_RPC_URL}"
bsc = "${BSC_RPC_URL}"
bsc_testnet = "${BSC_TESTNET_RPC_URL}"
abstract_mainnet = "${ABSTRACT_MAINNET_RPC_URL}"
abstract_testnet = "${ABSTRACT_TESTNET_RPC_URL}"
base_mainnet = "${BASE_MAINNET_RPC_URL}"
base_testnet = "${BASE_TESTNET_RPC_URL}"
merlin_mainnet = "${MERLIN_MAINNET_RPC_URL}"
merlin_testnet = "${MERLIN_TESTNET_RPC_URL}"
arbitrum_one = "${ARBITRUM_ONE_RPC_URL}"
arbitrum_testnet = "${ARBITRUM_TESTNET_RPC_URL}"
apechain_mainnet = "${APECHAIN_MAINNET_RPC_URL}"
apechain_testnet = "${APECHAIN_TESTNET_RPC_URL}"

[etherscan]
etherscan = {key = "${ETHERSCAN_API_KEY}"}
abstractscan_mainnet = {key = "${ABSTRACTSCAN_API_KEY}", url = "https://api.abscan.org/api"}
abstractscan_testnet = {key = "${ABSTRACTSCAN_API_KEY}", url = "https://api-sepolia.abscan.org/api"}
basescan_mainnet = {key = "${BASESCAN_API_KEY}", url = "https://api.basescan.org/api"}
basescan_testnet = {key = "${BASESCAN_API_KEY}", url = "https://api-sepolia.basescan.org/api"}
merlinscan_mainnet = {key = "${MERLINSCAN_API_KEY}", url = "https://scan.merlinchain.io/api"}
merlinscan_testnet = {key = "${MERLINSCAN_API_KEY}", url = "https://testnet-scan.merlinchain.io/api"}
arbiscan_one = {key = "${ARBISCAN_API_KEY}", url = "https://api.arbiscan.io/api"}
arbiscan_testnet = {key = "${ARBISCAN_API_KEY}", url = "https://api-sepolia.arbiscan.io/api"}
apescan_mainnet = {key = "${APESCAN_API_KEY}", url = "https://apechain.calderaexplorer.xyz/api"}
apescan_testnet = {key = "${APESCAN_API_KEY}", url = "https://curtis.explorer.caldera.xyz/api"}

[fmt]
line_length = 100
number_underscore = "thousands"
